on:
  issue_comment:
    types:
      - created

jobs:

  testing-farm:
    name: Verify tests pass (tf)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: dotnet-${{ github.event.issue.number }}-${{ matrix.dotnet_version }}-${{ matrix.arch }}-${{ matrix.compose }}
      cancel-in-progress: true

    strategy:
        fail-fast: false
        matrix:
          compose:
            - CentOS-Stream-9
            - CentOS-Stream-10
            - Fedora-41
            - Fedora-42
            - Fedora-Rawhide
            - RHEL-8-Nightly
            - RHEL-9-Nightly
            - RHEL-10-Nightly
          dotnet_version:
            - "8.0"
            - "9.0"
          arch:
            - "x86_64"
            - "aarch64"
          include:
            - compose: Fedora-42
              dotnet_version: "10.0"
              arch: "x86_64"
            - compose: Fedora-42
              dotnet_version: "10.0"
              arch: "aarch64"

    if: |
      github.event.issue.pull_request
      && contains(github.event.comment.body, '[test]')
      && contains(fromJson('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
      
    steps:
      - name: Check out code
        uses: actions/checkout@v4
          
      - name: Schedule tests on Testing Farm
        uses: sclorg/testing-farm-as-github-action@v3.1.2
        with:
          api_key: ${{ secrets.TF_API_KEY }}
          tmt_plan_regex: "ci"
          compose: ${{ matrix.compose }}
          arch: ${{ matrix.arch }}
          update_pull_request_status: true
          create_issue_comment: true
          pull_request_status_name: "${{ matrix.compose }} (${{ matrix.arch }}) - ${{ matrix.dotnet_version }}"
          variables: "dotnet_version=${{ matrix.dotnet_version }};arch=${{ matrix.arch }};REPO_URL=${{ github.server_url }}/${{ github.repository }};REPO_NAME=${{ github.repository }};"
          tf_scope: private
